Endpoint /api/search can return recommended books in response
ProductDock/rbc-library-search pull request #14
Opened 2022-05-25 12:00 UTC by natasatutuspd

2022-05-25 14:06 UTC, dusanpetrovicpd requested changes

2022-05-25 14:06 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/library/search/book/BookService.java
> +    public SearchBooksResponse getBooks(Optional<List<String>> topics, boolean recommended, int page) {
Let's create class (ie SearchFilters) that will encapsulate search parameters. That way, method would have only 1 parameter, and it's better for the future when search by title is introduced.

2022-05-25 14:06 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/library/search/kafka/consumer/KafkaConsumer.java
> +        bookService.updateBookRecommendations(bookRecommendedMessage);
It's better for method name to be "recommendBook". As parameter pass bookId instead of whole message

2022-05-26 09:01 UTC, milicazivkov85 requested changes
Add integration test in **BookSearchApiTest**

2022-05-27 10:44 UTC, milicazivkov85 approved these changes

2022-05-27 10:50 UTC, merged