Added book search by title and author
ProductDock/rbc-library-search pull request #19
Opened 2022-06-17 11:48 UTC by NenadBecanovicPD

2022-06-17 12:32 UTC, vukomanv-pd approved these changes

2022-06-23 06:59 UTC, dusanpetrovicpd requested changes

2022-06-23 06:59 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/library/search/integration/BookSearchApiTest.java
> +                    .andExpect(status().isOk())
Introduce new method for getting search suggestion in test

2022-06-23 07:09 UTC, milicazivkov approved these changes

2022-06-23 08:39 UTC, merged