Include book status when getting books
ProductDock/rbc-library-search pull request #8
Opened 2022-05-04 09:28 UTC by natasatutuspd

2022-05-04 11:45 UTC, NenadBecanovicPD commented on src/main/java/com/productdock/library/search/book/BookMapper.java
> +    }
Maybe move methods to BookDocument class?

2022-05-04 13:23 UTC, milicazivkov85 requested changes

2022-05-04 13:23 UTC, milicazivkov85 commented on src/main/java/com/productdock/library/search/book/BookMapper.java
> +    public BookDto toBookDto(BookDocument bookDocument) {
Extract till you drop:

In the end, `toBookDto()` should be simple as:
```
        var bookDto = new BookDto();
        mapSimpleProperties(bookDto, bookDocument);
        mapRecords(bookDto, bookDocument.getRecords());
        return bookDto;
```

Try to find other opportunities for extraction.

2022-05-04 13:23 UTC, milicazivkov85 commented on src/test/java/com/productdock/library/search/book/BookMapperShould.java
> +        List<Record> records = new ArrayList<>();
Setting up test object (BookDocument in this case) should be cleaner. Try using Builder pattern to set up entire BookDocument.

2022-05-06 05:31 UTC, milicazivkov85 approved these changes
It is approved, but please address this minor issues before merging.
I have added one additional commit, to make cleaner mother objects, that will allow use of fluent builder. See last commit. Test are failing because of the issue with toBookDto (it has side effects) but as soon as you fix it it will go green again.

2022-05-06 05:31 UTC, milicazivkov85 commented on src/main/java/com/productdock/library/search/book/BookMapper.java
> +        records.addAll(createAvailableRecords(availableBookCount));
toBookDto method violates Have no side effect rule. It alters the records collection belonging to the input parameter (BookDocument). 
You can fix this by changed the way list is combined:
```
        var availableRecords = createAvailableRecords(availableBookCount);
        var allRecords = Collections.join(records, availableRecords);
```
That way bookDocument.getRentalState().getRecords() will stay unchanged , and BookDto will still get combined records.

2022-05-06 11:12 UTC, merged